#+title: MY PERSONAL DOOM EMACS CONFIGURATION
#+author: Marcus
#+author: marcus@r38.se
#+attr_html: :width 30%;
[[file:images/doomEmacsTokyoNight.svg]]

This is my personal configuration of doom emacs. If you found it, don't use it. I normally push unfinished code to this git.

Here be dragons...

* Install Doom Emacs
#+begin_src sh
git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.config/emacs
~/.config/emacs/bin/doom install
#+end_src
* Get my configuration
#+begin_src sh
rm -rf ~/.config/doom
git clone https://github.com/marcus-38/doom ~/.config/doom
#+end_src
Next steps:
- Start Emacs and load config.org
- =SPC-.= or =C-x C-f= to load file
- load ~/.config/doom/config.org
- generate the configs by running =C-c C-v t= to tangle all the files
- load the new configuration =SPC h r r= or =~/.config/emacs/bin/doom sync= in the terminal
* One configuration file
See [[file:config.org][config.org]] for the source configuration file with some limited commentary. Work in progress...

** Generated files
Running =doom sync= in a terminal or =SPC h r r= in emacs generates the actual configuration files read by emacs:
- [[file:config.el][config.el]]
- [[file:init.el][init.el]]
- [[file:packages.el][packages.el]]

* References
This configuration relly on other people's files and from other resources. My top go to places when looking for insperation and solutions are:

- [[http://pages.sachachua.com/.emacs.d/Sacha.html][Sacha Chua's Emacs Configuration]]
- [[https://www.masteringemacs.org/][Mastering Emacs]]
- [[https://github.com/doomemacs/doomemacs/blob/master/docs/getting_started.org][Doom Emacs Getting Started Guide]]
- [[https://protesilaos.com/][Protesilaos Stavrou]]
- [[https://www.pygopar.com/][Pygopar]]
- [[https://github.com/emacs-tw/awesome-emacs][Awesome Emacs]]
